version: '3.7'
services:
  php:
    build:
      context: .docker/php
    volumes:
      - ./magento2:/var/www/html
  mysql:
    build:
      context: .docker/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=magento2
      - MYSQL_ROOT_PASSWORD=D4UnoP0dUxzf
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./magento2:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d

